name: AdminBroadcast
version: 0.1
main: net.madmanmarkau.AdminBroadcast.AdminBroadcast
commands:
  say:
    description: Broadcasts a message to all users.
    usage: /say <message>
  gsay:
    description: Broadcast a message to a specific group.
    usage: /gsay <group> <message>
  osay:
    description: Broadcast a message to all server ops, including console.
    usage: /osay <message>
